### ISSUE TITLE
feature: clicking on a button will add a new item to a list

### ISSUE THREAD

**Issue by Vhynn** [Vhynn/ToDoApp#6]
There are currently three "add item" buttons on the to do app, clicking these should ask for an issue to add, then add it to the end of the appropriate list (depending on which button was clicked)

**Comment by Vhynn** [comment]
Made a first pass at functional buttons (commit 7157189). They work but a few things I would like to change, some way to get user input without using `prompt()` unless there is a way to prompt without the big popup window. Also need to figure out a way to maybe save added items? Not sure how easy or realistic that goal is though. Finally I need to re-think the formatting of the final box probably, as it is (three separate `<ul>`) it might be hard to add items to it.

**Comment by jbradenbrown** [comment]
Nice! As an alternative to the prompt, you could use a text input element that gets added to the list and changed to text or somehow locked when you press enter or a confirm button. 

<img width="928" alt="Screen Shot 2022-11-17 at 6 21 23 PM" src="https://user-images.githubusercontent.com/977370/202588061-7419c23f-da0f-4821-ae2b-aaa3e3f99334.png">

Is there a specific way you had in mind for adding the text to the list?

Saving items will come later. Just focus on the functionality of adding something to the list after pressing the button for now.

**Comment by Vhynn** [comment]
Nothing specific yet, I do want the button to make _something_ appear that is used to add an issue and then isn't visible when done. I think I'm going to try to get the bottom button functional in a good way first and then I have a few ideas to try as alternatives to `prompt()`.
